redis:
  url: "redis://127.0.0.1:6379/0"

# چند دقیقه بن (ipset timeout)
ban_minutes: 10

# اگر true، IP قدیمی کاربر روی همه نودها هم drop شود
cross_node_ban: true

# پورت‌هایی که معمولاً Xray گوش می‌دهد (برای conntrack delete)
ports: [8080, 5540, 2222]

# حد پیش‌فرض (fallback) وقتی inbound در لیست تعریف نشده
fallback_limit: 1

# محدودیت هم‌زمانی برای inbound های خاص (می‌تواند خالی باشد)
inbounds_limit:


nodes:
  # نمونه—با منو اضافه می‌شود
  # - name: gcore-usa
  #   host: 203.0.113.10
  #   ssh_user: root
  #   ssh_port: 22
  #   ssh_key: /root/.ssh/id_rsa   # یا ssh_pass: "password"
  #   docker_container: marzban-node
